```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidyverse)
library(dplyr)
library(leaflet)
library(ggplot2)
library(wbstats)
library(janitor)
library(sp)
library(rgdal)
library(rgeos)
library(grid)
library(readxl)
library(maptools)
library(scales)
library(rstanarm)

all_dams <- read_rds("shiny_app/all_dams.rds")
all_wbstats <- read_rds("shiny_app/all_wbstats.rds")
joined <- read_rds("shiny_app/joined.rds")
subnational <- read_rds("shiny_app/subnational.rds")
file_path <- read_rds("shiny_app/file_path.rds")
gridded_data <- read_rds("shiny_app/gridded_data.rds")
```
```{r test}

country_names <- as.character(unique(file_path$country_name))

joined <- joined %>%
  filter(country %in% country_names) %>%
  drop_na(pop, gdp)
  

 dam_model <- stan_glm(data = joined, 
                         formula = dams_count ~ pop + gdp, 
                         family = gaussian(), 
                         refresh = 0)

 alo <- tibble(truth = joined$dams_count, forecast = predict(dam_model), year = joined$year)
 

 alo %>%
   pivot_longer(cols = c(truth, forecast),
                 names_to = "source", 
                 values_to = "value") %>%
   ggplot(aes(y = value, x = year, fill = source)) + 
   geom_col(size = 0.5, position = "dodge") + 
   labs(y = "Number of dams constructed", 
        x = "Year", 
        title = "Predicted vs. Real number of dams for a selection of countries 1960 - 2005", 
        subtitle = "Based on GDP and Population") +
  theme_light() 
```


```{r shapefiles}

mymap <- readOGR(path("India")) 

mymap@data <- mymap@data %>% 
  clean_names()

all_dams_new <- all_dams %>%
  drop_na(decimal_degree_latitude) %>%
  filter(country == "India")  %>%
  group_by(nearest_city) %>%
  mutate(dams_count = n()) 

admin_list <- as.tibble(subnational %>%
  filter(country_name == "India") %>%
  select(admin_name, population) %>%
  rename(admin_new = admin_name))

coordinates(all_dams_new) = c("decimal_degree_longitude","decimal_degree_latitude")
crs.geo1 = CRS("+proj=longlat")
proj4string(all_dams_new) = crs.geo1

id_agg = aggregate(x=all_dams_new["dams_count"],by = mymap, FUN = length)

qpal = colorBin("Reds", id_agg$dams_count, bins=4)


tibble(name = mymap@data$admin_name, count = id_agg@data$dams_count) 
list <- as.tibble(id_agg@data$dams_count)
bind_cols(admin_list, list)

leaflet(id_agg) %>%
  addPolygons(stroke = TRUE,opacity = 1,fillOpacity = 0.5, smoothFactor = 0.5,
              color="black",fillColor = ~qpal(dams_count),weight = 1) %>%
  addLegend(values=~dams_count,pal=qpal,title="Dams") %>%
  addCircleMarkers(data = all_dams %>% drop_na(decimal_degree_latitude) %>% filter(country == "India"), lat = ~ decimal_degree_latitude, lng = ~ decimal_degree_longitude, radius = 0.1)

unique(subnational$country_name)

make_population_choro("India")

```

```{r nn}

all_dams %>%
  group_by(year) %>%
  filter(year > 1990) 
  drop_na(reservoir_area_km2) %>%
  ggplot(aes(reservoir_area_km2)) + 
  geom_histogram(aes(y = after_stat(count/sum(count))),
                     bins = 150) + 
  labs(y = "Proportion", 
       x = "Reservoir Area in km2") +
  theme_light()

dam_years <- as.character(unique(all_dams$year))

all_dams %>%
arrange(desc(reservoir_area_km2)) %>%
  slice(1:1)

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = all_dams, lat = ~ decimal_degree_latitude, lng = ~ decimal_degree_longitude, radius = 0.1) %>%
  setView(lat = 0, lng = 0, zoom = 2)

basins <- readOGR(path("World Basins"))

make_population_choro <- function(country_name){
  
  country_dams <- all_dams %>%
    drop_na(decimal_degree_latitude) %>%
  filter(country == case_when(country_name == "World Basins" ~ country_names,
                              country_name != "World Basins" ~ country_name))
  
  mymap <- readOGR(dsn = path(country_name))
  
  crs.geo1 = CRS("+proj=longlat")
  proj4string(gridded_data) = crs.geo1
  proj4string(gridded_data) <- proj4string(mymap)
  grid_mymap <- gIntersects(gridded_data,mymap,byid = TRUE)
  
  mymap@data$total_pop <- apply(grid_mymap,1,function(x) sum(gridded_data@data$popgpw_2005_40[x]))
  
  pal <- colorNumeric(palette = "viridis", domain = mymap@data$population, reverse = TRUE)
  
  leaflet(mymap) %>%
    addPolygons(stroke = TRUE,opacity = 1,fillOpacity = 0.5, smoothFactor = 0.5, weight = 1, fillColor = ~pal(population))   %>%
    addLegend(values=~population,pal=pal,title="Population") %>%
    addCircleMarkers(data = country_dams, lat = ~ decimal_degree_latitude, lng = ~ decimal_degree_longitude, radius = 0.1)
  #add pop_up info
}

make_population_choro("India")
```